//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbanianXrm.SolutionPackager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlbanianXrm.SolutionPackager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string BTN_NO {
            get {
                return ResourceManager.GetString("BTN_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string BTN_YES {
            get {
                return ResourceManager.GetString("BTN_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Code {
            get {
                object obj = ResourceManager.GetObject("Code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Command {
            get {
                object obj = ResourceManager.GetObject("Command", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} package not found on {1}.
        /// </summary>
        public static string CORE_TOOLS_NOT_FOUND {
            get {
                return ResourceManager.GetString("CORE_TOOLS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting latest version of Core Tools.
        /// </summary>
        public static string DOWNLOADING_CORE_TOOLS {
            get {
                return ResourceManager.GetString("DOWNLOADING_CORE_TOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading solution &quot;{0}&quot;.
        /// </summary>
        public static string DOWNLOADING_SOLUTION {
            get {
                return ResourceManager.GetString("DOWNLOADING_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is one error.
        /// </summary>
        public static string EXPORT_ERROR {
            get {
                return ResourceManager.GetString("EXPORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} errors.
        /// </summary>
        public static string EXPORT_ERRORS {
            get {
                return ResourceManager.GetString("EXPORT_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting solution &quot;{0}&quot;.
        /// </summary>
        public static string EXTRACTING_SOLUTION {
            get {
                return ResourceManager.GetString("EXTRACTING_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clear the field value?.
        /// </summary>
        public static string FIELD_CLEAR_MESSAGE {
            get {
                return ResourceManager.GetString("FIELD_CLEAR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Field.
        /// </summary>
        public static string FIELD_CLEAR_TITLE {
            get {
                return ResourceManager.GetString("FIELD_CLEAR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution|*.zip|All Files|*.*.
        /// </summary>
        public static string FILTER_SOLUTION {
            get {
                return ResourceManager.GetString("FILTER_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text|*.txt|All Files|*.*.
        /// </summary>
        public static string FILTER_TEXT {
            get {
                return ResourceManager.GetString("FILTER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map|*.xml|All Files|*.*.
        /// </summary>
        public static string FILTER_XML {
            get {
                return ResourceManager.GetString("FILTER_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing Solution.
        /// </summary>
        public static string IMPORT_HEADER {
            get {
                return ResourceManager.GetString("IMPORT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing solution &quot;{0}&quot;.
        /// </summary>
        public static string IMPORT_SOLUTION {
            get {
                return ResourceManager.GetString("IMPORT_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started import job with id &apos;{0}&apos;.
        /// </summary>
        public static string IMPORT_STARTED {
            get {
                return ResourceManager.GetString("IMPORT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the input folder.
        /// </summary>
        public static string INPUT_FOLDER_NOT_SPECIFIED {
            get {
                return ResourceManager.GetString("INPUT_FOLDER_NOT_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch command line.
        /// </summary>
        public static string LAUNCH_COMMAND_LINE {
            get {
                return ResourceManager.GetString("LAUNCH_COMMAND_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Log {
            get {
                object obj = ResourceManager.GetObject("Log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MBOX_ERROR {
            get {
                return ResourceManager.GetString("MBOX_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string MBOX_INFORMATION {
            get {
                return ResourceManager.GetString("MBOX_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the solution to download.
        /// </summary>
        public static string NO_SOLUTION_SELECTED {
            get {
                return ResourceManager.GetString("NO_SOLUTION_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid NuGet feed.
        /// </summary>
        public static string NUGET_FEED_ERROR {
            get {
                return ResourceManager.GetString("NUGET_FEED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the output folder.
        /// </summary>
        public static string OUTPUT_FOLDER_NOT_SPECIFIED {
            get {
                return ResourceManager.GetString("OUTPUT_FOLDER_NOT_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing solution &quot;{0}&quot;.
        /// </summary>
        public static string PACKING_SOLUTION {
            get {
                return ResourceManager.GetString("PACKING_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program output.
        /// </summary>
        public static string PROGRAM_OUTPUT {
            get {
                return ResourceManager.GetString("PROGRAM_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string QUESTION {
            get {
                return ResourceManager.GetString("QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close this tab?.
        /// </summary>
        public static string QUESTION_CLOSE_TOOL {
            get {
                return ResourceManager.GetString("QUESTION_CLOSE_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing solution list.
        /// </summary>
        public static string REFRESHING_SOLUTION_LIST {
            get {
                return ResourceManager.GetString("REFRESHING_SOLUTION_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration settigns correctly loaded.
        /// </summary>
        public static string SETTINGS_FOUND {
            get {
                return ResourceManager.GetString("SETTINGS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration settings were not found.
        /// </summary>
        public static string SETTINGS_NOT_FOUND {
            get {
                return ResourceManager.GetString("SETTINGS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Configuration settings.
        /// </summary>
        public static string SETTINGS_SAVING {
            get {
                return ResourceManager.GetString("SETTINGS_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolutionPackager.exe is missing!.
        /// </summary>
        public static string SOLUTIONPACKAGER_MISSING {
            get {
                return ResourceManager.GetString("SOLUTIONPACKAGER_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Solutions {
            get {
                object obj = ResourceManager.GetObject("Solutions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Zip {
            get {
                object obj = ResourceManager.GetObject("Zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Zip File does not exist.
        /// </summary>
        public static string ZIP_FILE_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("ZIP_FILE_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip File was not specified.
        /// </summary>
        public static string ZIP_FILE_NOT_SPECIFIED {
            get {
                return ResourceManager.GetString("ZIP_FILE_NOT_SPECIFIED", resourceCulture);
            }
        }
    }
}
