//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbanianXrm.SolutionPackager.FormLocalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SolutionPackagerControl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SolutionPackagerControl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlbanianXrm.SolutionPackager.SolutionPackagerControl", typeof(SolutionPackagerControl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImageLayout similar to Stretch.
        /// </summary>
        internal static System.Windows.Forms.ImageLayout btnCoreTools_BackgroundImageLayout {
            get {
                object obj = ResourceManager.GetObject("btnCoreTools.BackgroundImageLayout", resourceCulture);
                return ((System.Windows.Forms.ImageLayout)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=386,Y=2}.
        /// </summary>
        internal static System.Drawing.Point btnCoreTools_Location {
            get {
                object obj = ResourceManager.GetObject("btnCoreTools.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=30, Height=30}.
        /// </summary>
        internal static System.Drawing.Size btnCoreTools_Size {
            get {
                object obj = ResourceManager.GetObject("btnCoreTools.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 10.
        /// </summary>
        internal static int btnCoreTools_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnCoreTools.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=341,Y=185}.
        /// </summary>
        internal static System.Drawing.Point btnExtract_Location {
            get {
                object obj = ResourceManager.GetObject("btnExtract.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        internal static System.Drawing.Size btnExtract_Size {
            get {
                object obj = ResourceManager.GetObject("btnExtract.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 10.
        /// </summary>
        internal static int btnExtract_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnExtract.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        internal static string btnExtract_Text {
            get {
                return ResourceManager.GetString("btnExtract.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImageLayout similar to Stretch.
        /// </summary>
        internal static System.Windows.Forms.ImageLayout btnNuGetFeed_BackgroundImageLayout {
            get {
                object obj = ResourceManager.GetObject("btnNuGetFeed.BackgroundImageLayout", resourceCulture);
                return ((System.Windows.Forms.ImageLayout)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=386,Y=32}.
        /// </summary>
        internal static System.Drawing.Point btnNuGetFeed_Location {
            get {
                object obj = ResourceManager.GetObject("btnNuGetFeed.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=30, Height=30}.
        /// </summary>
        internal static System.Drawing.Size btnNuGetFeed_Size {
            get {
                object obj = ResourceManager.GetObject("btnNuGetFeed.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 13.
        /// </summary>
        internal static int btnNuGetFeed_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnNuGetFeed.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImageLayout similar to Stretch.
        /// </summary>
        internal static System.Windows.Forms.ImageLayout btnOpenZip_BackgroundImageLayout {
            get {
                object obj = ResourceManager.GetObject("btnOpenZip.BackgroundImageLayout", resourceCulture);
                return ((System.Windows.Forms.ImageLayout)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=384,Y=24}.
        /// </summary>
        internal static System.Drawing.Point btnOpenZip_Location {
            get {
                object obj = ResourceManager.GetObject("btnOpenZip.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=30, Height=30}.
        /// </summary>
        internal static System.Drawing.Size btnOpenZip_Size {
            get {
                object obj = ResourceManager.GetObject("btnOpenZip.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        internal static int btnOpenZip_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnOpenZip.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImageLayout similar to Stretch.
        /// </summary>
        internal static System.Windows.Forms.ImageLayout btnOutputFolder_BackgroundImageLayout {
            get {
                object obj = ResourceManager.GetObject("btnOutputFolder.BackgroundImageLayout", resourceCulture);
                return ((System.Windows.Forms.ImageLayout)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=384,Y=56}.
        /// </summary>
        internal static System.Drawing.Point btnOutputFolder_Location {
            get {
                object obj = ResourceManager.GetObject("btnOutputFolder.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=30, Height=30}.
        /// </summary>
        internal static System.Drawing.Size btnOutputFolder_Size {
            get {
                object obj = ResourceManager.GetObject("btnOutputFolder.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        internal static int btnOutputFolder_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnOutputFolder.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImageLayout similar to Stretch.
        /// </summary>
        internal static System.Windows.Forms.ImageLayout btnRefreshSolutions_BackgroundImageLayout {
            get {
                object obj = ResourceManager.GetObject("btnRefreshSolutions.BackgroundImageLayout", resourceCulture);
                return ((System.Windows.Forms.ImageLayout)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=386,Y=12}.
        /// </summary>
        internal static System.Drawing.Point btnRefreshSolutions_Location {
            get {
                object obj = ResourceManager.GetObject("btnRefreshSolutions.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=30, Height=30}.
        /// </summary>
        internal static System.Drawing.Size btnRefreshSolutions_Size {
            get {
                object obj = ResourceManager.GetObject("btnRefreshSolutions.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        internal static int btnRefreshSolutions_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnRefreshSolutions.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkAllowWrite_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkAllowWrite.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleRight.
        /// </summary>
        internal static System.Drawing.ContentAlignment chkAllowWrite_CheckAlign {
            get {
                object obj = ResourceManager.GetObject("chkAllowWrite.CheckAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=7,Y=96}.
        /// </summary>
        internal static System.Drawing.Point chkAllowWrite_Location {
            get {
                object obj = ResourceManager.GetObject("chkAllowWrite.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=98, Height=19}.
        /// </summary>
        internal static System.Drawing.Size chkAllowWrite_Size {
            get {
                object obj = ResourceManager.GetObject("chkAllowWrite.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 12.
        /// </summary>
        internal static int chkAllowWrite_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkAllowWrite.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Write?  .
        /// </summary>
        internal static string chkAllowWrite_Text {
            get {
                return ResourceManager.GetString("chkAllowWrite.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkExportAutoNumbering_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkExportAutoNumbering.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=10,Y=77}.
        /// </summary>
        internal static System.Drawing.Point chkExportAutoNumbering_Location {
            get {
                object obj = ResourceManager.GetObject("chkExportAutoNumbering.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=116, Height=19}.
        /// </summary>
        internal static System.Drawing.Size chkExportAutoNumbering_Size {
            get {
                object obj = ResourceManager.GetObject("chkExportAutoNumbering.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        internal static int chkExportAutoNumbering_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkExportAutoNumbering.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Numbering.
        /// </summary>
        internal static string chkExportAutoNumbering_Text {
            get {
                return ResourceManager.GetString("chkExportAutoNumbering.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkExportCalendar_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkExportCalendar.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=153,Y=77}.
        /// </summary>
        internal static System.Drawing.Point chkExportCalendar_Location {
            get {
                object obj = ResourceManager.GetObject("chkExportCalendar.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=73, Height=19}.
        /// </summary>
        internal static System.Drawing.Size chkExportCalendar_Size {
            get {
                object obj = ResourceManager.GetObject("chkExportCalendar.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 10.
        /// </summary>
        internal static int chkExportCalendar_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkExportCalendar.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string chkExportCalendar_Text {
            get {
                return ResourceManager.GetString("chkExportCalendar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkExportCustomization_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkExportCustomization.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=294,Y=77}.
        /// </summary>
        internal static System.Drawing.Point chkExportCustomization_Location {
            get {
                object obj = ResourceManager.GetObject("chkExportCustomization.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=103, Height=19}.
        /// </summary>
        internal static System.Drawing.Size chkExportCustomization_Size {
            get {
                object obj = ResourceManager.GetObject("chkExportCustomization.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 11.
        /// </summary>
        internal static int chkExportCustomization_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkExportCustomization.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customization.
        /// </summary>
        internal static string chkExportCustomization_Text {
            get {
                return ResourceManager.GetString("chkExportCustomization.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkExportEmailTracking_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkExportEmailTracking.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=10,Y=102}.
        /// </summary>
        internal static System.Drawing.Point chkExportEmailTracking_Location {
            get {
                object obj = ResourceManager.GetObject("chkExportEmailTracking.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=102, Height=19}.
        /// </summary>
        internal static System.Drawing.Size chkExportEmailTracking_Size {
            get {
                object obj = ResourceManager.GetObject("chkExportEmailTracking.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 12.
        /// </summary>
        internal static int chkExportEmailTracking_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkExportEmailTracking.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Tracking.
        /// </summary>
        internal static string chkExportEmailTracking_Text {
            get {
                return ResourceManager.GetString("chkExportEmailTracking.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkExportExternalApplications_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkExportExternalApplications.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=153,Y=102}.
        /// </summary>
        internal static System.Drawing.Point chkExportExternalApplications_Location {
            get {
                object obj = ResourceManager.GetObject("chkExportExternalApplications.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=137, Height=19}.
        /// </summary>
        internal static System.Drawing.Size chkExportExternalApplications_Size {
            get {
                object obj = ResourceManager.GetObject("chkExportExternalApplications.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 13.
        /// </summary>
        internal static int chkExportExternalApplications_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkExportExternalApplications.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Applications.
        /// </summary>
        internal static string chkExportExternalApplications_Text {
            get {
                return ResourceManager.GetString("chkExportExternalApplications.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkExportGeneralSettings_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkExportGeneralSettings.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=294,Y=102}.
        /// </summary>
        internal static System.Drawing.Point chkExportGeneralSettings_Location {
            get {
                object obj = ResourceManager.GetObject("chkExportGeneralSettings.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=111, Height=19}.
        /// </summary>
        internal static System.Drawing.Size chkExportGeneralSettings_Size {
            get {
                object obj = ResourceManager.GetObject("chkExportGeneralSettings.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 14.
        /// </summary>
        internal static int chkExportGeneralSettings_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkExportGeneralSettings.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string chkExportGeneralSettings_Text {
            get {
                return ResourceManager.GetString("chkExportGeneralSettings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkExportISVConfig_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkExportISVConfig.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=10,Y=127}.
        /// </summary>
        internal static System.Drawing.Point chkExportISVConfig_Location {
            get {
                object obj = ResourceManager.GetObject("chkExportISVConfig.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=81, Height=19}.
        /// </summary>
        internal static System.Drawing.Size chkExportISVConfig_Size {
            get {
                object obj = ResourceManager.GetObject("chkExportISVConfig.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 15.
        /// </summary>
        internal static int chkExportISVConfig_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkExportISVConfig.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISV Config.
        /// </summary>
        internal static string chkExportISVConfig_Text {
            get {
                return ResourceManager.GetString("chkExportISVConfig.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkExportMarketing_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkExportMarketing.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=153,Y=127}.
        /// </summary>
        internal static System.Drawing.Point chkExportMarketing_Location {
            get {
                object obj = ResourceManager.GetObject("chkExportMarketing.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=80, Height=19}.
        /// </summary>
        internal static System.Drawing.Size chkExportMarketing_Size {
            get {
                object obj = ResourceManager.GetObject("chkExportMarketing.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 16.
        /// </summary>
        internal static int chkExportMarketing_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkExportMarketing.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        internal static string chkExportMarketing_Text {
            get {
                return ResourceManager.GetString("chkExportMarketing.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkExportOutlookSynchronization_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkExportOutlookSynchronization.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=153,Y=152}.
        /// </summary>
        internal static System.Drawing.Point chkExportOutlookSynchronization_Location {
            get {
                object obj = ResourceManager.GetObject("chkExportOutlookSynchronization.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=150, Height=19}.
        /// </summary>
        internal static System.Drawing.Size chkExportOutlookSynchronization_Size {
            get {
                object obj = ResourceManager.GetObject("chkExportOutlookSynchronization.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 17.
        /// </summary>
        internal static int chkExportOutlookSynchronization_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkExportOutlookSynchronization.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook Syncronization.
        /// </summary>
        internal static string chkExportOutlookSynchronization_Text {
            get {
                return ResourceManager.GetString("chkExportOutlookSynchronization.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkExportRelationshipRoles_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkExportRelationshipRoles.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=10,Y=152}.
        /// </summary>
        internal static System.Drawing.Point chkExportRelationshipRoles_Location {
            get {
                object obj = ResourceManager.GetObject("chkExportRelationshipRoles.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=122, Height=19}.
        /// </summary>
        internal static System.Drawing.Size chkExportRelationshipRoles_Size {
            get {
                object obj = ResourceManager.GetObject("chkExportRelationshipRoles.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 19.
        /// </summary>
        internal static int chkExportRelationshipRoles_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkExportRelationshipRoles.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Roles.
        /// </summary>
        internal static string chkExportRelationshipRoles_Text {
            get {
                return ResourceManager.GetString("chkExportRelationshipRoles.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkExportSales_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkExportSales.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=294,Y=127}.
        /// </summary>
        internal static System.Drawing.Point chkExportSales_Location {
            get {
                object obj = ResourceManager.GetObject("chkExportSales.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=52, Height=19}.
        /// </summary>
        internal static System.Drawing.Size chkExportSales_Size {
            get {
                object obj = ResourceManager.GetObject("chkExportSales.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 18.
        /// </summary>
        internal static int chkExportSales_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkExportSales.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string chkExportSales_Text {
            get {
                return ResourceManager.GetString("chkExportSales.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=93,Y=16}.
        /// </summary>
        internal static System.Drawing.Point cmbCrmSolutions_Location {
            get {
                object obj = ResourceManager.GetObject("cmbCrmSolutions.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=270, Height=23}.
        /// </summary>
        internal static System.Drawing.Size cmbCrmSolutions_Size {
            get {
                object obj = ResourceManager.GetObject("cmbCrmSolutions.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int cmbCrmSolutions_TabIndex {
            get {
                object obj = ResourceManager.GetObject("cmbCrmSolutions.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string cmbLanguage_Items {
            get {
                return ResourceManager.GetString("cmbLanguage.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        internal static string cmbLanguage_Items1 {
            get {
                return ResourceManager.GetString("cmbLanguage.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=110,Y=67}.
        /// </summary>
        internal static System.Drawing.Point cmbLanguage_Location {
            get {
                object obj = ResourceManager.GetObject("cmbLanguage.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=270, Height=23}.
        /// </summary>
        internal static System.Drawing.Size cmbLanguage_Size {
            get {
                object obj = ResourceManager.GetObject("cmbLanguage.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 16.
        /// </summary>
        internal static int cmbLanguage_TabIndex {
            get {
                object obj = ResourceManager.GetObject("cmbLanguage.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        internal static System.Drawing.Point errorProvider_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("errorProvider.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=212}.
        /// </summary>
        internal static System.Drawing.Point grpExportSolution_Location {
            get {
                object obj = ResourceManager.GetObject("grpExportSolution.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=432, Height=178}.
        /// </summary>
        internal static System.Drawing.Size grpExportSolution_Size {
            get {
                object obj = ResourceManager.GetObject("grpExportSolution.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 11.
        /// </summary>
        internal static int grpExportSolution_TabIndex {
            get {
                object obj = ResourceManager.GetObject("grpExportSolution.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Solution.
        /// </summary>
        internal static string grpExportSolution_Text {
            get {
                return ResourceManager.GetString("grpExportSolution.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=5,Y=10}.
        /// </summary>
        internal static System.Drawing.Point label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=100, Height=15}.
        /// </summary>
        internal static System.Drawing.Size label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        internal static int label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoreTools Version.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblAllowDelete_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblAllowDelete.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=7,Y=8}.
        /// </summary>
        internal static System.Drawing.Point lblAllowDelete_Location {
            get {
                object obj = ResourceManager.GetObject("lblAllowDelete.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=73, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblAllowDelete_Size {
            get {
                object obj = ResourceManager.GetObject("lblAllowDelete.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int lblAllowDelete_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblAllowDelete.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Delete.
        /// </summary>
        internal static string lblAllowDelete_Text {
            get {
                return ResourceManager.GetString("lblAllowDelete.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblExportAs_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblExportAs.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=7,Y=50}.
        /// </summary>
        internal static System.Drawing.Point lblExportAs_Location {
            get {
                object obj = ResourceManager.GetObject("lblExportAs.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=63, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblExportAs_Size {
            get {
                object obj = ResourceManager.GetObject("lblExportAs.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 22.
        /// </summary>
        internal static int lblExportAs_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblExportAs.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export As: .
        /// </summary>
        internal static string lblExportAs_Text {
            get {
                return ResourceManager.GetString("lblExportAs.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblExtractZipPath_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblExtractZipPath.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=7,Y=32}.
        /// </summary>
        internal static System.Drawing.Point lblExtractZipPath_Location {
            get {
                object obj = ResourceManager.GetObject("lblExtractZipPath.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=78, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblExtractZipPath_Size {
            get {
                object obj = ResourceManager.GetObject("lblExtractZipPath.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        internal static int lblExtractZipPath_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblExtractZipPath.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Path.
        /// </summary>
        internal static string lblExtractZipPath_Text {
            get {
                return ResourceManager.GetString("lblExtractZipPath.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblLanguage_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblLanguage.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode lblLanguage_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lblLanguage.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=5,Y=70}.
        /// </summary>
        internal static System.Drawing.Point lblLanguage_Location {
            get {
                object obj = ResourceManager.GetObject("lblLanguage.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=59, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblLanguage_Size {
            get {
                object obj = ResourceManager.GetObject("lblLanguage.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 15.
        /// </summary>
        internal static int lblLanguage_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblLanguage.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lblLanguage_Text {
            get {
                return ResourceManager.GetString("lblLanguage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblNuGetFeed_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblNuGetFeed.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=5,Y=40}.
        /// </summary>
        internal static System.Drawing.Point lblNuGetFeed_Location {
            get {
                object obj = ResourceManager.GetObject("lblNuGetFeed.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=69, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblNuGetFeed_Size {
            get {
                object obj = ResourceManager.GetObject("lblNuGetFeed.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 12.
        /// </summary>
        internal static int lblNuGetFeed_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblNuGetFeed.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet Feed.
        /// </summary>
        internal static string lblNuGetFeed_Text {
            get {
                return ResourceManager.GetString("lblNuGetFeed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblOnlineSolution_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblOnlineSolution.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=19}.
        /// </summary>
        internal static System.Drawing.Point lblOnlineSolution_Location {
            get {
                object obj = ResourceManager.GetObject("lblOnlineSolution.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=80, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblOnlineSolution_Size {
            get {
                object obj = ResourceManager.GetObject("lblOnlineSolution.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        internal static int lblOnlineSolution_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblOnlineSolution.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM Solution.
        /// </summary>
        internal static string lblOnlineSolution_Text {
            get {
                return ResourceManager.GetString("lblOnlineSolution.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblOutputFolder_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblOutputFolder.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=7,Y=64}.
        /// </summary>
        internal static System.Drawing.Point lblOutputFolder_Location {
            get {
                object obj = ResourceManager.GetObject("lblOutputFolder.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=81, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblOutputFolder_Size {
            get {
                object obj = ResourceManager.GetObject("lblOutputFolder.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int lblOutputFolder_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblOutputFolder.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        internal static string lblOutputFolder_Text {
            get {
                return ResourceManager.GetString("lblOutputFolder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool localOrCrm_AutoSize {
            get {
                object obj = ResourceManager.GetObject("localOrCrm.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleRight.
        /// </summary>
        internal static System.Drawing.ContentAlignment localOrCrm_CheckAlign {
            get {
                object obj = ResourceManager.GetObject("localOrCrm.CheckAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=7,Y=7}.
        /// </summary>
        internal static System.Drawing.Point localOrCrm_Location {
            get {
                object obj = ResourceManager.GetObject("localOrCrm.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=271, Height=19}.
        /// </summary>
        internal static System.Drawing.Size localOrCrm_Size {
            get {
                object obj = ResourceManager.GetObject("localOrCrm.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int localOrCrm_TabIndex {
            get {
                object obj = ResourceManager.GetObject("localOrCrm.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the solution from the Organization?.
        /// </summary>
        internal static string localOrCrm_Text {
            get {
                return ResourceManager.GetString("localOrCrm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution|*.zip|All Files|*.*.
        /// </summary>
        internal static string openZipFile_Filter {
            get {
                return ResourceManager.GetString("openZipFile.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=257,Y=17}.
        /// </summary>
        internal static System.Drawing.Point openZipFile_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("openZipFile.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=120}.
        /// </summary>
        internal static System.Drawing.Point panel1_Location {
            get {
                object obj = ResourceManager.GetObject("panel1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=432, Height=31}.
        /// </summary>
        internal static System.Drawing.Size panel1_Size {
            get {
                object obj = ResourceManager.GetObject("panel1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 13.
        /// </summary>
        internal static int panel1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("panel1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool radAllowDeleteNo_AutoSize {
            get {
                object obj = ResourceManager.GetObject("radAllowDeleteNo.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=211,Y=8}.
        /// </summary>
        internal static System.Drawing.Point radAllowDeleteNo_Location {
            get {
                object obj = ResourceManager.GetObject("radAllowDeleteNo.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=41, Height=19}.
        /// </summary>
        internal static System.Drawing.Size radAllowDeleteNo_Size {
            get {
                object obj = ResourceManager.GetObject("radAllowDeleteNo.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int radAllowDeleteNo_TabIndex {
            get {
                object obj = ResourceManager.GetObject("radAllowDeleteNo.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string radAllowDeleteNo_Text {
            get {
                return ResourceManager.GetString("radAllowDeleteNo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool radAllowDeletePrompt_AutoSize {
            get {
                object obj = ResourceManager.GetObject("radAllowDeletePrompt.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=92,Y=8}.
        /// </summary>
        internal static System.Drawing.Point radAllowDeletePrompt_Location {
            get {
                object obj = ResourceManager.GetObject("radAllowDeletePrompt.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=65, Height=19}.
        /// </summary>
        internal static System.Drawing.Size radAllowDeletePrompt_Size {
            get {
                object obj = ResourceManager.GetObject("radAllowDeletePrompt.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        internal static int radAllowDeletePrompt_TabIndex {
            get {
                object obj = ResourceManager.GetObject("radAllowDeletePrompt.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt.
        /// </summary>
        internal static string radAllowDeletePrompt_Text {
            get {
                return ResourceManager.GetString("radAllowDeletePrompt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool radAllowDeleteYes_AutoSize {
            get {
                object obj = ResourceManager.GetObject("radAllowDeleteYes.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=163,Y=8}.
        /// </summary>
        internal static System.Drawing.Point radAllowDeleteYes_Location {
            get {
                object obj = ResourceManager.GetObject("radAllowDeleteYes.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=42, Height=19}.
        /// </summary>
        internal static System.Drawing.Size radAllowDeleteYes_Size {
            get {
                object obj = ResourceManager.GetObject("radAllowDeleteYes.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int radAllowDeleteYes_TabIndex {
            get {
                object obj = ResourceManager.GetObject("radAllowDeleteYes.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string radAllowDeleteYes_Text {
            get {
                return ResourceManager.GetString("radAllowDeleteYes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool radManaged_AutoSize {
            get {
                object obj = ResourceManager.GetObject("radManaged.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=172,Y=48}.
        /// </summary>
        internal static System.Drawing.Point radManaged_Location {
            get {
                object obj = ResourceManager.GetObject("radManaged.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=19}.
        /// </summary>
        internal static System.Drawing.Size radManaged_Size {
            get {
                object obj = ResourceManager.GetObject("radManaged.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 21.
        /// </summary>
        internal static int radManaged_TabIndex {
            get {
                object obj = ResourceManager.GetObject("radManaged.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed.
        /// </summary>
        internal static string radManaged_Text {
            get {
                return ResourceManager.GetString("radManaged.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool radUnmanaged_AutoSize {
            get {
                object obj = ResourceManager.GetObject("radUnmanaged.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=76,Y=48}.
        /// </summary>
        internal static System.Drawing.Point radUnmanaged_Location {
            get {
                object obj = ResourceManager.GetObject("radUnmanaged.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=90, Height=19}.
        /// </summary>
        internal static System.Drawing.Size radUnmanaged_Size {
            get {
                object obj = ResourceManager.GetObject("radUnmanaged.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 20.
        /// </summary>
        internal static int radUnmanaged_TabIndex {
            get {
                object obj = ResourceManager.GetObject("radUnmanaged.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmanaged.
        /// </summary>
        internal static string radUnmanaged_Text {
            get {
                return ResourceManager.GetString("radUnmanaged.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=140,Y=17}.
        /// </summary>
        internal static System.Drawing.Point selectFolder_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("selectFolder.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle splitContainer1_Dock {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool splitContainer1_IsSplitterFixed {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.IsSplitterFixed", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        internal static System.Drawing.Point splitContainer1_Location {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=800, Height=600}.
        /// </summary>
        internal static System.Drawing.Size splitContainer1_Size {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 440.
        /// </summary>
        internal static int splitContainer1_SplitterDistance {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.SplitterDistance", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int splitContainer1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=4,Y=24}.
        /// </summary>
        internal static System.Drawing.Point tabExtract_Location {
            get {
                object obj = ResourceManager.GetObject("tabExtract.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=3,Top=3,Right=3,Bottom=3}.
        /// </summary>
        internal static System.Windows.Forms.Padding tabExtract_Padding {
            get {
                object obj = ResourceManager.GetObject("tabExtract.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=432, Height=572}.
        /// </summary>
        internal static System.Drawing.Size tabExtract_Size {
            get {
                object obj = ResourceManager.GetObject("tabExtract.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int tabExtract_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabExtract.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        internal static string tabExtract_Text {
            get {
                return ResourceManager.GetString("tabExtract.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=4,Y=24}.
        /// </summary>
        internal static System.Drawing.Point tabPack_Location {
            get {
                object obj = ResourceManager.GetObject("tabPack.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=3,Top=3,Right=3,Bottom=3}.
        /// </summary>
        internal static System.Windows.Forms.Padding tabPack_Padding {
            get {
                object obj = ResourceManager.GetObject("tabPack.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=432, Height=572}.
        /// </summary>
        internal static System.Drawing.Size tabPack_Size {
            get {
                object obj = ResourceManager.GetObject("tabPack.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int tabPack_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabPack.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        internal static string tabPack_Text {
            get {
                return ResourceManager.GetString("tabPack.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=4,Y=24}.
        /// </summary>
        internal static System.Drawing.Point tabSettings_Location {
            get {
                object obj = ResourceManager.GetObject("tabSettings.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=3,Top=3,Right=3,Bottom=3}.
        /// </summary>
        internal static System.Windows.Forms.Padding tabSettings_Padding {
            get {
                object obj = ResourceManager.GetObject("tabSettings.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=432, Height=572}.
        /// </summary>
        internal static System.Drawing.Size tabSettings_Size {
            get {
                object obj = ResourceManager.GetObject("tabSettings.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int tabSettings_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabSettings.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string tabSettings_Text {
            get {
                return ResourceManager.GetString("tabSettings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle tabsExtractOrPack_Dock {
            get {
                object obj = ResourceManager.GetObject("tabsExtractOrPack.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Segoe UI, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font tabsExtractOrPack_Font {
            get {
                object obj = ResourceManager.GetObject("tabsExtractOrPack.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        internal static System.Drawing.Point tabsExtractOrPack_Location {
            get {
                object obj = ResourceManager.GetObject("tabsExtractOrPack.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=440, Height=600}.
        /// </summary>
        internal static System.Drawing.Size tabsExtractOrPack_Size {
            get {
                object obj = ResourceManager.GetObject("tabsExtractOrPack.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int tabsExtractOrPack_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabsExtractOrPack.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=110,Y=6}.
        /// </summary>
        internal static System.Drawing.Point txtCoreTools_Location {
            get {
                object obj = ResourceManager.GetObject("txtCoreTools.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool txtCoreTools_Multiline {
            get {
                object obj = ResourceManager.GetObject("txtCoreTools.Multiline", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.RichTextBoxScrollBars similar to None.
        /// </summary>
        internal static System.Windows.Forms.RichTextBoxScrollBars txtCoreTools_ScrollBars {
            get {
                object obj = ResourceManager.GetObject("txtCoreTools.ScrollBars", resourceCulture);
                return ((System.Windows.Forms.RichTextBoxScrollBars)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=270, Height=24}.
        /// </summary>
        internal static System.Drawing.Size txtCoreTools_Size {
            get {
                object obj = ResourceManager.GetObject("txtCoreTools.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        internal static int txtCoreTools_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtCoreTools.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtCoreTools_Text {
            get {
                return ResourceManager.GetString("txtCoreTools.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool txtCoreTools_WordWrap {
            get {
                object obj = ResourceManager.GetObject("txtCoreTools.WordWrap", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=110,Y=36}.
        /// </summary>
        internal static System.Drawing.Point txtNuGetFeed_Location {
            get {
                object obj = ResourceManager.GetObject("txtNuGetFeed.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool txtNuGetFeed_Multiline {
            get {
                object obj = ResourceManager.GetObject("txtNuGetFeed.Multiline", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.RichTextBoxScrollBars similar to None.
        /// </summary>
        internal static System.Windows.Forms.RichTextBoxScrollBars txtNuGetFeed_ScrollBars {
            get {
                object obj = ResourceManager.GetObject("txtNuGetFeed.ScrollBars", resourceCulture);
                return ((System.Windows.Forms.RichTextBoxScrollBars)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=270, Height=24}.
        /// </summary>
        internal static System.Drawing.Size txtNuGetFeed_Size {
            get {
                object obj = ResourceManager.GetObject("txtNuGetFeed.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 11.
        /// </summary>
        internal static int txtNuGetFeed_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtNuGetFeed.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://packages.nuget.org/api/v2.
        /// </summary>
        internal static string txtNuGetFeed_Text {
            get {
                return ResourceManager.GetString("txtNuGetFeed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool txtNuGetFeed_WordWrap {
            get {
                object obj = ResourceManager.GetObject("txtNuGetFeed.WordWrap", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle txtOutput_Dock {
            get {
                object obj = ResourceManager.GetObject("txtOutput.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        internal static System.Drawing.Point txtOutput_Location {
            get {
                object obj = ResourceManager.GetObject("txtOutput.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=356, Height=600}.
        /// </summary>
        internal static System.Drawing.Size txtOutput_Size {
            get {
                object obj = ResourceManager.GetObject("txtOutput.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int txtOutput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtOutput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtOutput_Text {
            get {
                return ResourceManager.GetString("txtOutput.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=92,Y=60}.
        /// </summary>
        internal static System.Drawing.Point txtOutputFolder_Location {
            get {
                object obj = ResourceManager.GetObject("txtOutputFolder.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool txtOutputFolder_Multiline {
            get {
                object obj = ResourceManager.GetObject("txtOutputFolder.Multiline", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.RichTextBoxScrollBars similar to None.
        /// </summary>
        internal static System.Windows.Forms.RichTextBoxScrollBars txtOutputFolder_ScrollBars {
            get {
                object obj = ResourceManager.GetObject("txtOutputFolder.ScrollBars", resourceCulture);
                return ((System.Windows.Forms.RichTextBoxScrollBars)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=270, Height=24}.
        /// </summary>
        internal static System.Drawing.Size txtOutputFolder_Size {
            get {
                object obj = ResourceManager.GetObject("txtOutputFolder.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        internal static int txtOutputFolder_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtOutputFolder.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtOutputFolder_Text {
            get {
                return ResourceManager.GetString("txtOutputFolder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool txtOutputFolder_WordWrap {
            get {
                object obj = ResourceManager.GetObject("txtOutputFolder.WordWrap", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=94,Y=28}.
        /// </summary>
        internal static System.Drawing.Point txtZipPath_Location {
            get {
                object obj = ResourceManager.GetObject("txtZipPath.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool txtZipPath_Multiline {
            get {
                object obj = ResourceManager.GetObject("txtZipPath.Multiline", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.RichTextBoxScrollBars similar to None.
        /// </summary>
        internal static System.Windows.Forms.RichTextBoxScrollBars txtZipPath_ScrollBars {
            get {
                object obj = ResourceManager.GetObject("txtZipPath.ScrollBars", resourceCulture);
                return ((System.Windows.Forms.RichTextBoxScrollBars)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=270, Height=24}.
        /// </summary>
        internal static System.Drawing.Size txtZipPath_Size {
            get {
                object obj = ResourceManager.GetObject("txtZipPath.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int txtZipPath_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtZipPath.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtZipPath_Text {
            get {
                return ResourceManager.GetString("txtZipPath.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool txtZipPath_WordWrap {
            get {
                object obj = ResourceManager.GetObject("txtZipPath.WordWrap", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
